feature_engineering_task:
  description: >
    Perform feature engineering on the cleaned dataset (clean_data.csv).
    Create new features like profit margins, price per unit, and categorical encodings.
    Save the enhanced dataset as features.csv.
  expected_output: >
    An enhanced dataset (features.csv) with engineered features ready for machine learning.
  agent: FeatureEngineerAgent

model_training_task:
  description: >
    Train a machine learning model using the engineered features (features.csv).
    Use appropriate algorithms for profit prediction.
    Save the trained model as trained_model.pkl.
  expected_output: >
    A trained machine learning model saved as trained_model.pkl.
  agent: ModelTrainerAgent

evaluation_task:
  description: >
    Evaluate the trained model's performance using cross-validation and test metrics.
    Generate a comprehensive evaluation report (evaluation_report.md).
  expected_output: >
    A detailed evaluation report (evaluation_report.md) with performance metrics and analysis.
  agent: ModelEvaluatorAgent

model_card_task:
  description: >
    Create a comprehensive model card documenting the model's purpose, performance, and limitations.
    Generate model_card.md for model documentation and governance.
  expected_output: >
    A complete model card (model_card.md) with model documentation and ethical considerations.
  agent: ModelCardAgent
